-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 18:33:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vk` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vk` ;

-- -----------------------------------------------------
-- Table `vk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(145) NOT NULL COMMENT 'Имя',
  `lastname` VARCHAR(145) NOT NULL COMMENT 'Фамилия',
  `email` VARCHAR(245) NOT NULL,
  `phone` BIGINT(45) NOT NULL,
  `password_hash` CHAR(65) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`media_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`media_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`communities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`communities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NOT NULL,
  `description` VARCHAR(245) NULL DEFAULT NULL,
  `admin_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_communities_users1_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_communities_users1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`likes` (
  `users_id` INT UNSIGNED NOT NULL,
  `communities_id` INT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `deleted` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_new_likes_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  INDEX `fk_new_likes_communities1_idx` (`communities_id` ASC) VISIBLE,
  CONSTRAINT `fk_new_likes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_new_likes_communities1`
    FOREIGN KEY (`communities_id`)
    REFERENCES `vk`.`communities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `media_types_id` INT UNSIGNED NOT NULL,
  `likes_users_id` INT UNSIGNED NULL,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  `blob` BLOB NULL DEFAULT NULL,
  `size` BIGINT NOT NULL DEFAULT 0,
  `metadata` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_media_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_media_media_types1_idx` (`media_types_id` ASC) VISIBLE,
  INDEX `fk_media_new_likes1_idx` (`likes_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_media_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_media_types1`
    FOREIGN KEY (`media_types_id`)
    REFERENCES `vk`.`media_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_new_likes1`
    FOREIGN KEY (`likes_users_id`)
    REFERENCES `vk`.`likes` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`profiles` (
  `users_id` INT UNSIGNED NOT NULL,
  `likes_users_id` INT UNSIGNED NULL,
  `photo_id` INT UNSIGNED NULL DEFAULT NULL,
  `gender` ENUM('m', 'w', 'x') NOT NULL,
  `birthday` DATE NOT NULL,
  `adress` VARCHAR(245) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_profiles_users_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  INDEX `fk_profiles_media1_idx` (`photo_id` ASC) VISIBLE,
  INDEX `fk_profiles_new_likes1_idx` (`likes_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_media1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `vk`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_new_likes1`
    FOREIGN KEY (`likes_users_id`)
    REFERENCES `vk`.`likes` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`friend_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`friend_requests` (
  `form_users_id` INT UNSIGNED NOT NULL,
  `to_users_id` INT UNSIGNED NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '-1 - отклонено, 0 - запрос, 1 - принято',
  `created_ad` DATETIME NULL DEFAULT NOW() COMMENT 'Когда создался запрос в друзья',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT 'Время, когда отклонили или приняли запрос на дружбу',
  INDEX `fk_friend_requests_users1_idx` (`form_users_id` ASC) VISIBLE,
  INDEX `fk_friend_requests_users2_idx` (`to_users_id` ASC) VISIBLE,
  PRIMARY KEY (`form_users_id`, `to_users_id`),
  CONSTRAINT `fk_friend_requests_users1`
    FOREIGN KEY (`form_users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_requests_users2`
    FOREIGN KEY (`to_users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_users_id` INT UNSIGNED NOT NULL,
  `to_users_id` INT UNSIGNED NOT NULL,
  `media_id` INT UNSIGNED NOT NULL,
  `likes_users_id` INT UNSIGNED NULL,
  `text` VARCHAR(245) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `from_users_idx` (`from_users_id` ASC) VISIBLE,
  INDEX `fk_message_users1_idx` (`to_users_id` ASC) VISIBLE,
  INDEX `fk_message_media1_idx` (`media_id` ASC) VISIBLE,
  INDEX `fk_message_likes1_idx` (`likes_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_users_from`
    FOREIGN KEY (`from_users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_users_to`
    FOREIGN KEY (`to_users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `vk`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_likes1`
    FOREIGN KEY (`likes_users_id`)
    REFERENCES `vk`.`likes` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`users_communities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`users_communities` (
  `communities_id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  INDEX `fk_users_communities_communities1_idx` (`communities_id` ASC) VISIBLE,
  INDEX `fk_users_communities_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`communities_id`, `users_id`),
  CONSTRAINT `fk_users_communities_communities1`
    FOREIGN KEY (`communities_id`)
    REFERENCES `vk`.`communities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_communities_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `communities_id` INT UNSIGNED NULL DEFAULT NULL,
  `media_id` INT UNSIGNED NOT NULL,
  `likes_users_id` INT UNSIGNED NULL,
  `text` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_posts_communities1_idx` (`communities_id` ASC) VISIBLE,
  INDEX `fk_posts_media1_idx` (`media_id` ASC) VISIBLE,
  INDEX `fk_posts_new_likes1_idx` (`likes_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_communities1`
    FOREIGN KEY (`communities_id`)
    REFERENCES `vk`.`communities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `vk`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_new_likes1`
    FOREIGN KEY (`likes_users_id`)
    REFERENCES `vk`.`likes` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
